import pandas as pd
import streamlit as st

# إعدادات الصفحة المتقدمة
st.set_page_config(
    page_title="Ultimate Car Intelligence & Market Suite",
    page_icon="🚗",
    layout="wide",
)

# قاعدة بيانات شاملة وموسعة تشمل جميع الماركات والموديلات والفئات واستهلاك الوقود والسيولة
CAR_MODELS = {
    "Hyundai": {
        "Elantra": {
            "price": 1300000,
            "category": "Sedan",
            "fuel_rate": 7.2,
            "liquidity": "High",
        },
        "Tucson": {
            "price": 1900000,
            "category": "SUV",
            "fuel_rate": 8.1,
            "liquidity": "High",
        },
        "Accent": {
            "price": 900000,
            "category": "Sedan",
            "fuel_rate": 6.5,
            "liquidity": "High",
        },
        "Creta": {
            "price": 1400000,
            "category": "SUV",
            "fuel_rate": 7.5,
            "liquidity": "Medium",
        },
        "I10": {
            "price": 700000,
            "category": "Hatchback",
            "fuel_rate": 5.5,
            "liquidity": "High",
        },
        "Sonata": {
            "price": 1700000,
            "category": "Sedan",
            "fuel_rate": 8.0,
            "liquidity": "Medium",
        },
        "Santa Fe": {
            "price": 2400000,
            "category": "SUV",
            "fuel_rate": 9.2,
            "liquidity": "Medium",
        },
        "Bayon": {
            "price": 1150000,
            "category": "SUV",
            "fuel_rate": 6.7,
            "liquidity": "High",
        },
    },
    "Kia": {
        "Cerato / K3": {
            "price": 1350000,
            "category": "Sedan",
            "fuel_rate": 7.0,
            "liquidity": "High",
        },
        "Sportage": {
            "price": 1950000,
            "category": "SUV",
            "fuel_rate": 8.2,
            "liquidity": "High",
        },
        "Pegas": {
            "price": 850000,
            "category": "Sedan",
            "fuel_rate": 6.0,
            "liquidity": "High",
        },
        "Seltos": {
            "price": 1500000,
            "category": "SUV",
            "fuel_rate": 7.6,
            "liquidity": "Medium",
        },
        "XCeed": {
            "price": 1600000,
            "category": "Hatchback",
            "fuel_rate": 7.1,
            "liquidity": "Medium",
        },
        "Sorento": {
            "price": 2500000,
            "category": "SUV",
            "fuel_rate": 9.5,
            "liquidity": "Medium",
        },
        "Soul": {
            "price": 1100000,
            "category": "Hatchback",
            "fuel_rate": 7.0,
            "liquidity": "Medium",
        },
    },
    "Toyota": {
        "Corolla": {
            "price": 1600000,
            "category": "Sedan",
            "fuel_rate": 6.8,
            "liquidity": "High",
        },
        "Yaris": {
            "price": 1000000,
            "category": "Hatchback",
            "fuel_rate": 5.2,
            "liquidity": "High",
        },
        "Fortuner": {
            "price": 3800000,
            "category": "SUV",
            "fuel_rate": 11.0,
            "liquidity": "High",
        },
        "C-HR": {
            "price": 1750000,
            "category": "SUV",
            "fuel_rate": 6.0,
            "liquidity": "Medium",
        },
        "Belta": {
            "price": 850000,
            "category": "Sedan",
            "fuel_rate": 6.4,
            "liquidity": "Medium",
        },
        "Camry": {
            "price": 2800000,
            "category": "Sedan",
            "fuel_rate": 8.5,
            "liquidity": "Medium",
        },
        "RAV4": {
            "price": 2900000,
            "category": "SUV",
            "fuel_rate": 7.5,
            "liquidity": "High",
        },
        "Land Cruiser": {
            "price": 6500000,
            "category": "SUV",
            "fuel_rate": 14.0,
            "liquidity": "High",
        },
    },
    "Nissan": {
        "Sunny": {
            "price": 800000,
            "category": "Sedan",
            "fuel_rate": 6.9,
            "liquidity": "High",
        },
        "Sentra": {
            "price": 1100000,
            "category": "Sedan",
            "fuel_rate": 7.1,
            "liquidity": "High",
        },
        "Qashqai": {
            "price": 1650000,
            "category": "SUV",
            "fuel_rate": 7.4,
            "liquidity": "Medium",
        },
        "Juke": {
            "price": 1300000,
            "category": "SUV",
            "fuel_rate": 6.3,
            "liquidity": "Medium",
        },
        "Patrol": {
            "price": 5500000,
            "category": "SUV",
            "fuel_rate": 14.5,
            "liquidity": "Medium",
        },
        "X-Trail": {
            "price": 2100000,
            "category": "SUV",
            "fuel_rate": 8.0,
            "liquidity": "Medium",
        },
    },
    "Honda": {
        "Civic": {
            "price": 1700000,
            "category": "Sedan",
            "fuel_rate": 6.7,
            "liquidity": "High",
        },
        "City": {
            "price": 1200000,
            "category": "Sedan",
            "fuel_rate": 6.1,
            "liquidity": "High",
        },
        "CR-V": {
            "price": 2200000,
            "category": "SUV",
            "fuel_rate": 7.8,
            "liquidity": "High",
        },
        "Accord": {
            "price": 2400000,
            "category": "Sedan",
            "fuel_rate": 8.0,
            "liquidity": "Medium",
        },
        "HR-V": {
            "price": 1750000,
            "category": "SUV",
            "fuel_rate": 6.5,
            "liquidity": "Medium",
        },
    },
    "Mitsubishi": {
        "Lancer": {
            "price": 750000,
            "category": "Sedan",
            "fuel_rate": 7.5,
            "liquidity": "High",
        },
        "Xpander": {
            "price": 1300000,
            "category": "SUV",
            "fuel_rate": 7.6,
            "liquidity": "High",
        },
        "Eclipse Cross": {
            "price": 1600000,
            "category": "SUV",
            "fuel_rate": 8.0,
            "liquidity": "Medium",
        },
        "Attrage": {
            "price": 750000,
            "category": "Sedan",
            "fuel_rate": 5.0,
            "liquidity": "Medium",
        },
        "Pajero": {
            "price": 3500000,
            "category": "SUV",
            "fuel_rate": 13.0,
            "liquidity": "Medium",
        },
    },
    "Suzuki": {
        "Swift": {
            "price": 750000,
            "category": "Hatchback",
            "fuel_rate": 5.0,
            "liquidity": "High",
        },
        "Ciaz": {
            "price": 850000,
            "category": "Sedan",
            "fuel_rate": 5.8,
            "liquidity": "High",
        },
        "Ertiga": {
            "price": 950000,
            "category": "SUV",
            "fuel_rate": 6.8,
            "liquidity": "High",
        },
        "Espresso": {
            "price": 550000,
            "category": "Hatchback",
            "fuel_rate": 4.8,
            "liquidity": "High",
        },
        "Vitara": {
            "price": 1250000,
            "category": "SUV",
            "fuel_rate": 6.3,
            "liquidity": "Medium",
        },
        "Jimny": {
            "price": 1400000,
            "category": "SUV",
            "fuel_rate": 7.8,
            "liquidity": "High",
        },
    },
    "BMW": {
        "3 Series (320i)": {
            "price": 3500000,
            "category": "Luxury",
            "fuel_rate": 7.8,
            "liquidity": "High",
        },
        "5 Series (520i)": {
            "price": 4800000,
            "category": "Luxury",
            "fuel_rate": 8.4,
            "liquidity": "Medium",
        },
        "X1": {
            "price": 2900000,
            "category": "SUV",
            "fuel_rate": 7.5,
            "liquidity": "High",
        },
        "X5": {
            "price": 6200000,
            "category": "Luxury",
            "fuel_rate": 10.5,
            "liquidity": "Medium",
        },
        "4 Series": {
            "price": 4500000,
            "category": "Luxury",
            "fuel_rate": 8.0,
            "liquidity": "Medium",
        },
        "7 Series": {
            "price": 8500000,
            "category": "Luxury",
            "fuel_rate": 11.2,
            "liquidity": "Low",
        },
    },
    "Mercedes": {
        "C-Class (C180/C200)": {
            "price": 4200000,
            "category": "Luxury",
            "fuel_rate": 7.3,
            "liquidity": "High",
        },
        "E-Class (E200)": {
            "price": 5800000,
            "category": "Luxury",
            "fuel_rate": 8.0,
            "liquidity": "Medium",
        },
        "A-Class": {
            "price": 2700000,
            "category": "Hatchback",
            "fuel_rate": 6.2,
            "liquidity": "Medium",
        },
        "GLC": {
            "price": 5900000,
            "category": "SUV",
            "fuel_rate": 9.0,
            "liquidity": "High",
        },
        "S-Class": {
            "price": 9500000,
            "category": "Luxury",
            "fuel_rate": 11.5,
            "liquidity": "Low",
        },
        "G-Class": {
            "price": 12000000,
            "category": "SUV",
            "fuel_rate": 15.0,
            "liquidity": "High",
        },
    },
    "Audi": {
        "A4": {
            "price": 2800000,
            "category": "Luxury",
            "fuel_rate": 7.0,
            "liquidity": "Medium",
        },
        "A6": {
            "price": 3900000,
            "category": "Luxury",
            "fuel_rate": 8.2,
            "liquidity": "Medium",
        },
        "Q3": {
            "price": 2500000,
            "category": "SUV",
            "fuel_rate": 7.3,
            "liquidity": "High",
        },
        "Q7": {
            "price": 4900000,
            "category": "SUV",
            "fuel_rate": 10.0,
            "liquidity": "Medium",
        },
        "Q5": {
            "price": 3700000,
            "category": "SUV",
            "fuel_rate": 8.0,
            "liquidity": "High",
        },
    },
    "Volkswagen": {
        "Golf": {
            "price": 1700000,
            "category": "Hatchback",
            "fuel_rate": 6.5,
            "liquidity": "High",
        },
        "Passat": {
            "price": 1900000,
            "category": "Sedan",
            "fuel_rate": 7.0,
            "liquidity": "Medium",
        },
        "Tiguan": {
            "price": 2500000,
            "category": "SUV",
            "fuel_rate": 7.9,
            "liquidity": "High",
        },
        "Jetta": {
            "price": 900000,
            "category": "Sedan",
            "fuel_rate": 6.8,
            "liquidity": "Medium",
        },
        "Touareg": {
            "price": 3800000,
            "category": "SUV",
            "fuel_rate": 10.5,
            "liquidity": "Medium",
        },
    },
    "Skoda": {
        "Octavia": {
            "price": 1850000,
            "category": "Sedan",
            "fuel_rate": 6.3,
            "liquidity": "High",
        },
        "Kodiaq": {
            "price": 2600000,
            "category": "SUV",
            "fuel_rate": 8.1,
            "liquidity": "High",
        },
        "Karoq": {
            "price": 2100000,
            "category": "SUV",
            "fuel_rate": 7.2,
            "liquidity": "Medium",
        },
        "Scala": {
            "price": 1300000,
            "category": "Hatchback",
            "fuel_rate": 5.8,
            "liquidity": "Medium",
        },
        "Superb": {
            "price": 2400000,
            "category": "Sedan",
            "fuel_rate": 7.1,
            "liquidity": "Medium",
        },
    },
    "Renault": {
        "Logan": {
            "price": 650000,
            "category": "Sedan",
            "fuel_rate": 6.4,
            "liquidity": "High",
        },
        "Megane": {
            "price": 1400000,
            "category": "Sedan",
            "fuel_rate": 6.6,
            "liquidity": "High",
        },
        "Duster": {
            "price": 1200000,
            "category": "SUV",
            "fuel_rate": 7.8,
            "liquidity": "High",
        },
        "Stepway": {
            "price": 850000,
            "category": "Hatchback",
            "fuel_rate": 6.7,
            "liquidity": "High",
        },
        "Kadjar": {
            "price": 1500000,
            "category": "SUV",
            "fuel_rate": 7.0,
            "liquidity": "Medium",
        },
    },
    "Peugeot": {
        "301": {
            "price": 850000,
            "category": "Sedan",
            "fuel_rate": 6.5,
            "liquidity": "High",
        },
        "508": {
            "price": 1800000,
            "category": "Sedan",
            "fuel_rate": 7.2,
            "liquidity": "Medium",
        },
        "2008": {
            "price": 1450000,
            "category": "SUV",
            "fuel_rate": 6.2,
            "liquidity": "Medium",
        },
        "3008": {
            "price": 1950000,
            "category": "SUV",
            "fuel_rate": 7.0,
            "liquidity": "High",
        },
        "5008": {
            "price": 2200000,
            "category": "SUV",
            "fuel_rate": 7.6,
            "liquidity": "Medium",
        },
    },
    "Chevrolet": {
        "Aveo": {
            "price": 600000,
            "category": "Sedan",
            "fuel_rate": 7.3,
            "liquidity": "High",
        },
        "Optra": {
            "price": 750000,
            "category": "Sedan",
            "fuel_rate": 7.5,
            "liquidity": "High",
        },
        "Captiva": {
            "price": 1500000,
            "category": "SUV",
            "fuel_rate": 8.2,
            "liquidity": "Medium",
        },
        "Malibu": {
            "price": 1400000,
            "category": "Sedan",
            "fuel_rate": 7.2,
            "liquidity": "Medium",
        },
        "Tahoe": {
            "price": 5500000,
            "category": "SUV",
            "fuel_rate": 13.5,
            "liquidity": "Low",
        },
    },
    "Fiat": {
        "Tipo": {
            "price": 1050000,
            "category": "Sedan",
            "fuel_rate": 6.3,
            "liquidity": "High",
        },
        "500": {
            "price": 1100000,
            "category": "Hatchback",
            "fuel_rate": 5.8,
            "liquidity": "Medium",
        },
    },
    "MG": {
        "MG 5": {
            "price": 850000,
            "category": "Sedan",
            "fuel_rate": 6.8,
            "liquidity": "High",
        },
        "MG 6": {
            "price": 1200000,
            "category": "Sedan",
            "fuel_rate": 7.0,
            "liquidity": "High",
        },
        "MG ZS": {
            "price": 1050000,
            "category": "SUV",
            "fuel_rate": 7.2,
            "liquidity": "High",
        },
        "MG RX5": {
            "price": 1400000,
            "category": "SUV",
            "fuel_rate": 8.0,
            "liquidity": "Medium",
        },
        "MG4": {
            "price": 1350000,
            "category": "Hatchback",
            "fuel_rate": 4.5,
            "liquidity": "Medium",
        },
        "MG HS": {
            "price": 1600000,
            "category": "SUV",
            "fuel_rate": 8.3,
            "liquidity": "Medium",
        },
    },
    "Chery": {
        "Arrizo 5": {
            "price": 750000,
            "category": "Sedan",
            "fuel_rate": 7.0,
            "liquidity": "High",
        },
        "Tiggo 3": {
            "price": 880000,
            "category": "SUV",
            "fuel_rate": 7.7,
            "liquidity": "High",
        },
        "Tiggo 7": {
            "price": 1100000,
            "category": "SUV",
            "fuel_rate": 7.5,
            "liquidity": "High",
        },
        "Tiggo 8": {
            "price": 1450000,
            "category": "SUV",
            "fuel_rate": 8.3,
            "liquidity": "Medium",
        },
        "Tiggo 4 Pro": {
            "price": 980000,
            "category": "SUV",
            "fuel_rate": 7.1,
            "liquidity": "High",
        },
    },
    "Geely": {
        "Emgrand": {
            "price": 850000,
            "category": "Sedan",
            "fuel_rate": 6.7,
            "liquidity": "Medium",
        },
        "Coolray": {
            "price": 1300000,
            "category": "SUV",
            "fuel_rate": 6.6,
            "liquidity": "High",
        },
        "Okavango": {
            "price": 1650000,
            "category": "SUV",
            "fuel_rate": 8.0,
            "liquidity": "Medium",
        },
        "Monjaro": {
            "price": 2100000,
            "category": "SUV",
            "fuel_rate": 8.5,
            "liquidity": "Medium",
        },
    },
    "Changan": {
        "Alsvin": {
            "price": 650000,
            "category": "Sedan",
            "fuel_rate": 6.2,
            "liquidity": "High",
        },
        "CS35 Plus": {
            "price": 1150000,
            "category": "SUV",
            "fuel_rate": 7.0,
            "liquidity": "High",
        },
        "CS55 Plus": {
            "price": 1350000,
            "category": "SUV",
            "fuel_rate": 7.5,
            "liquidity": "Medium",
        },
        "Uni-T": {
            "price": 1500000,
            "category": "SUV",
            "fuel_rate": 7.8,
            "liquidity": "Medium",
        },
        "Uni-V": {
            "price": 1550000,
            "category": "Sedan",
            "fuel_rate": 7.4,
            "liquidity": "Medium",
        },
    },
    "BYD": {
        "F3": {
            "price": 620000,
            "category": "Sedan",
            "fuel_rate": 6.5,
            "liquidity": "High",
        },
        "Song Plus": {
            "price": 1600000,
            "category": "SUV",
            "fuel_rate": 5.0,
            "liquidity": "High",
        },
        "Atto 3": {
            "price": 1700000,
            "category": "SUV",
            "fuel_rate": 4.2,
            "liquidity": "Medium",
        },
    },
    "HAVAL": {
        "H6": {
            "price": 1450000,
            "category": "SUV",
            "fuel_rate": 8.0,
            "liquidity": "High",
        },
        "Jolion": {
            "price": 1200000,
            "category": "SUV",
            "fuel_rate": 7.2,
            "liquidity": "High",
        },
        "H6 GT": {
            "price": 1650000,
            "category": "SUV",
            "fuel_rate": 8.3,
            "liquidity": "Medium",
        },
    },
    "Jetour": {
        "X70": {
            "price": 1250000,
            "category": "SUV",
            "fuel_rate": 8.0,
            "liquidity": "High",
        },
        "X70 Plus": {
            "price": 1450000,
            "category": "SUV",
            "fuel_rate": 8.2,
            "liquidity": "Medium",
        },
        "Dashing": {
            "price": 1500000,
            "category": "SUV",
            "fuel_rate": 7.9,
            "liquidity": "High",
        },
    },
}

CAR_IMAGES = {
    "BMW": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
    "Mercedes": "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80",
    "Toyota": "https://images.unsplash.com/photo-1629897048514-3dd7414fe72a?auto=format&fit=crop&w=800&q=80",
    "Hyundai": "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80",
    "Kia": "https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?auto=format&fit=crop&w=800&q=80",
    "Nissan": "https://images.unsplash.com/photo-1609521263047-"
},